spring.application.name=smartdocs

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB